---
- hosts: localhost
  connection: local
  become: yes
  become_user: root

  vars_files:
    - /tmp/vars.json

  pre_tasks:
    - name: "Install packages"
      apt: 
        name:
          - curl
          - jq
        state: present

  tasks:  
    - name: "Install monitoring agent"
      shell: 
        cmd: |
          cd /tmp
          curl -k https://{{ proxy_ip }}/downloads/salt/telegraf-utils.sh --output telegraf-utils.sh
          chmod +x telegraf-utils.sh
          export token=`curl -X POST https://{{ ops_ip }}}/suite-api/api/auth/token/acquire?_no_links=true -H "accept: application/json" -H "Content-Type: application/json" -d '{ "username" : "{{ ops_user }}", "password" : "{{ ops_password }}" }' | jq .token`
          ./telegraf-utils.sh product-managed -c {{ proxy_ip }} -v {{ ops_ip }} -t $token
          rm telegraf-utils.sh