---
- hosts: localhost
  connection: local
  become: yes
  become_user: root

  vars_files:
    - /tmp/vars.json

  pre_tasks:
     tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install software-properties-common
      ansible.builtin.apt:
        name: software-properties-common
        state: present

    - name: Add MySQL APT repository
      ansible.builtin.apt_repository:
        repo: 'deb http://repo.mysql.com/apt/ubuntu/ focal mysql-5.7'
        state: present
        update_cache: yes

    - name: Install MySQL APT GPG key
      ansible.builtin.apt_key:
        url: 'https://repo.mysql.com/RPM-GPG-KEY-mysql'
        state: present

    - name: Install MySQL Server 5.7
      ansible.builtin.apt:
        name: mysql-server
        state: present
        force_apt_get: yes

    - name: "Install MySQL Server 5.7"
      apt:
        name:
          - mysql-server-5.7
          - mysql-client
          - libmysqlclient-dev
          - unzip
          - opem-vm-tools
        state: present
        update_cache: yes  
