---
- hosts: localhost
  connection: local
  become: yes
  become_user: root

  vars_files:
    - /tmp/vars.json

  pre_tasks:
  #  - name: "Add mysql 5.7 apt repository"
  #    apt_repository:
  #     repo: 'deb http://archive.ubuntu.com/ubuntu main universe multiverse restricted'
  #     state: present
  #      update_cache: yes

    - name: "Install MySQL Server 5.7"
      apt:
        name:
          - mysql-server
          - mysql-client
          - unzip
        state: present
        update_cache: yes  

  tasks:
    - name: "Create MySQL config files"
      copy:
        content: |
          [client]
          user=root
          password={{ dbpassword }}
          user=ocuser
          password={{ dbpassword }}
        dest: "/etc/mysql/mysql.conf.d/mysqld.cnf"
        append: yes
        owner: root
        group: root
        mode: 0644

    - name: "Start and enable services"
      service: "name={{ item }} state=restarted enabled=yes"
      with_items:
        - mysql
    
    - name "Create database user"
      mysql_user:
        name: "{{ dbuser }}"
        password: "{{ dbpassword }}"
        priv: "*.*:ALL"

    - name: "Create database"
      mysql_db:
        name: "opencart"
        state: present
        login_user: root
        login_password: "{{ dbpassword }}"