---
- hosts: localhost
  connection: local
  become: yes
  become_user: root

  vars_files:
    - /tmp/vars.json

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Add public key mysql from ubuntu server
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: 467B942D3A79BD29
    - name: add mysql 5.7 apt repository
      apt_repository:
        repo: 'deb http://repo.mysql.com/apt/ubuntu bionic mysql-5.7'
        state: present
        update_cache: yes

    - name: "Install MySQL Server 5.7"
      apt:
        name:
          - mysql-server
          - mysql-client
          - unzip
          - opem-vm-tools
        state: present
        update_cache: yes  
