---
- hosts: localhost
  connection: local
  become: yes
  become_user: root

  # Set up app monitoring
- import_playbook: app-monitoring.yaml

  vars_files:
    - /tmp/vars.json

  pre_tasks:
  #  - name: "Add mysql 5.7 apt repository"
  #    apt_repository:
  #     repo: 'deb http://archive.ubuntu.com/ubuntu main universe multiverse restricted'
  #     state: present
  #      update_cache: yes

    - name: Wait for automatic system updates
      shell: "while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 1; done;"

    - name: "Install MySQL Server"    
      apt:
        name:
          - mysql-server
          - mysql-client
          - python3-mysqldb
          - unzip
          - net-tools
        state: present
        update_cache: yes  

    - name: "Create MySQL config files"
      blockinfile:
        content: |
          [client]
          user=root
          password={{ db_password }}
          user=ocuser
          password={{ db_password }}
        dest: "/etc/mysql/mysql.conf.d/mysqld.cnf"

    - name: "Bind MySQL socket to all interfaces"
      replace:  
        path: '/etc/mysql/mysql.conf.d/mysqld.cnf'
        regexp: '^\s*bind-address'
        replace: '#bind-address'

    - name: "Start and enable services"
      service: "name={{ item }} state=restarted enabled=yes"
      with_items:
        - mysql
    
    - name: "Create database user"
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "*.*:ALL"
        state: present

    - name: "Flush database privileges"
      command: "mysql -e \"update mysql.user set host = '%' where user = 'ocuser'; flush privileges;\""

    - name: "Create database"
      mysql_db:
        name: "opencart"
        state: present
        login_user: root
        login_password: "{{ db_password }}"