---
- hosts: localhost
  connection: local
  become: yes
  become_user: root

  vars_files:
    - /tmp/vars.json
    - /tmp/env.json

  pre_tasks:
    - name: "Add pa:ondrej/php repository"
      apt_repository:
        repo: "ppa:ondrej/php"
        state: present
        update_cache: yes

    - name: "Install packages"
      apt: 
        name:
          - apache2
          - git
          - php7.2
          - php7.2-mysql
          - libapache2-mod-php
          - php7.2-cli
          - php7.2-common
          - php7.2-intl
          - php7.2-gd
          - php7.2-mbstring
          - php7.2-xml
          - php7.2-zip
          - php7.2-curl
          - php7.2-xmlrpc
          - unzip
          - open-vm-tools
          - mysql-client

  tasks:
    - name: "Copy current IP to my_ip"
      set_fact:
        my_ip: "{{ ansible_default_ipv4.address }}"
    - name: "Clone OpenCart demo from Github"
      git:
        repo: "https://github.com/jsenicka/opencart-demo.git"
        depth: 1
        dest: "/tmp/opencart"

    - name: "Move OpenCart files to /var/www"
      command: "mv /tmp/opencart /var/www/"

    - name: "Set owner and permissions on /var/www/opencart"
      file:
        path: "/var/www/opencart"
        recurse: yes
        state: directory
        owner: www-data
        group: www-data
        mode: 0775

    - name: "Write apache configuration to opencart.conf"
      copy:
        content: |
          <VirtualHost *:80>
            ServerName www.opencart.vcf.local
            DocumentRoot /var/www/opencart
            <Directory /var/www/opencart/>
              AllowOverride All
              allow from all
            </Directory>
          </VirtualHost>
          <VirtualHost *:8080>
            ServerName www.opencart.vcf.local
            DocumentRoot /var/www/opencart
            <Directory /var/www/opencart/>
              AllowOverride All
              allow from all
            </Directory>
          </VirtualHost>
        dest: "/etc/apache2/sites-available/opencart.conf"

    - name: "Create mysql.cnf"
      copy:
        content: |
          [client]
          user={{ db_user }}
          password={{ db_password }}
        dest: "/etc/mysql/conf.d/mysqld.cnf"

    - name: "Set up database username"
      replace:
        path: "{{ item }}"
        regexp: "usernamehere"
        replace: "{{ db_user }}"
      with_items:
        - /var/www/opencart/config.php
        - /var/www/opencart/admin/config.php

    - name: "Set up DB password"
      replace:
        path: "{{ item }}"
        regexp: "passwordhere"
        replace: "{{ db_password }}"
      with_items:
        - /var/www/opencart/config.php
        - /var/www/opencart/admin/config.php

    - name: "Set up frontend IP"
      replace:  
        path: "{{ item }}"
        regexp: "frontendiphere"
        replace: "{{ my_ip }}"
      with_items:
        - /var/www/opencart/config.php
        - /var/www/opencart/admin/config.php

    - name: "Set up DB IP"
      replace:
        path: '{{ item }}'
        regexp: 'dbiphere'
        replace: '{{ db_ip }}'
      with_items:
        - /var/www/opencart/config.php
        - /var/www/opencart/admin/config.php

    - name: "Copy OpenCart files to /var/www/html"
      command: "{{ item }}"
      with_items:
        - a2ensite opencart.conf
        - a2dissite 000-default.conf
        - a2dismod php8.3
        - mysql -u {{ db_user }} -h {{ db_ip }} -e 'source /var/www/opencart/install/opencart.sql'
        - mysql -u {{ db_user }} -h {{ db_ip }} -e "INSERT INTO oc_user (user_id,user_group_id,username,password,salt,firstname,lastname,email,image,code,ip,status,date_added) VALUES (1,1,'admin','5feaa046f6927df3d744007ec1491dba838f672e','c4wnfrq9J','demo','user','admin@admin.com','none','none','none',1,'2019-01-31 06:29:09')" opencart

    - name: "Start and enable services"
      service: "name={{ item }} state=restarted enabled=yes"
      with_items:
        - apache2
        - ssh