---
- hosts: localhost
  connection: local
  become: yes
  become_user: root

  pre_tasks:
    - name: "Install packages"
      apt: 
        name:
          - apache2
          - git
          - php
          - php-mysql
          - libapache2-mod-php
          - php-cli
          - php-common
          - php-intl
          - php-gd
          - php-mbstring
          - php-xml
          - php-zip
          - php-curl
          - php-xmlrpc
          - unzip
          - open-vm-tools

  tasks:
    - name: "Pull OpenCart demo from Github"
      git:
        repo: "https://github.com/jsenicka/opencart-demo.git"
        dest: "/tmp/opencart"
    - name: "Create an application user named ocuser"
      user:
        name: "ocuser"
        password: "VMware123!"
        shell: "/bin/bash"
        groups: "sudo"

    - name: "Copy OpenCart files to /var/www/html"
      command: "{{ item }}"
      with_items:
        - mv /tmp/opencart /var/www/opencart
        - chown -R www-data.www-data /var/www/opencart
        - chmod -R 755 /var/www/opencart
        - PASS=VMware123!
        - sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/g" /etc/ssh/sshd_config
        - service ssh reload
        - hostnamectl set-hostname ${self.resourceName}
        - git clone https://github.com/jsenicka/opencart-demo.git /tmp/opencart
        - sleep 30
        - mv /tmp/opencart /var/www/
        - chown -R www-data.www-data /var/www/opencart
        - chmod -R 775 /var/www/opencart
        - tee /etc/apache2/sites-available/opencart.conf > /dev/null << EOF
        - <VirtualHost *:80>
        -   ServerName www.opencart.vcf.local
        -   DocumentRoot /var/www/opencart
        -   <Directory /var/www/opencart/>
        -     AllowOverride All
        -     allow from all
        -   </Directory>
        - </VirtualHost>
        - <VirtualHost *:8080>
        -   ServerName www.opencart.vcf.local
        -   DocumentRoot /var/www/opencart
        -   <Directory /var/www/opencart/>
        -     AllowOverride All
        -     allow from all
        -   </Directory>
        - </VirtualHost>
        - EOF
        - cd /etc/apache2/sites-available/
        - a2ensite opencart.conf
        - a2dissite 000-default.conf
        - systemctl reload apache2
        - systemctl restart apache2
        - echo "[client]" >> /etc/mysql/mysql.conf.d/mysqld.cnf
        - echo "user=ocuser" >> /etc/mysql/mysql.conf.d/mysqld.cnf
        - echo "password=$PASS" >> /etc/mysql/mysql.conf.d/mysqld.cnf
        - export onpremip=$(ip route get 8.8.8.8 | awk -F"src " 'NR==1{split($2,a," ");print a[1]}')
        - MySQLip=${resource.OC-MySQL-Auto.networks[0].address}
        - export ip4=$onpremip
        - sed -i "s/MOAD Electronic Super Store/Holodeck Aria Assembler Fixed Network Lab/g" /var/www/opencart/install/opencart.sql
        - mysql -u $USER -h $MySQLip -e 'source /var/www/opencart/install/opencart.sql'
        - mysql -u $USER -h $MySQLip -e "INSERT INTO oc_user (user_id,user_group_id,username,password,salt,firstname,lastname,email,image,code,ip,status,date_added) VALUES (1,1,'admin','5feaa046f6927df3d744007ec1491dba838f672e','c4wnfrq9J','demo','user','admin@admin.com','none','none','none',1,'2019-01-31 06:29:09')" opencart
        - sed -i "s/frontendiphere/$ip4/g" /var/www/opencart/config.php
        - sed -i "s/dbiphere/$MySQLip/g" /var/www/opencart/config.php
        - sed -i "s/usernamehere/$USER/g" /var/www/opencart/config.php
        - sed -i "s/passwordhere/$PASS/g" /var/www/opencart/config.php
        - sed -i "s/frontendiphere/$ip4/g" /var/www/opencart/admin/config.php
        - sed -i "s/dbiphere/$MySQLip/g" /var/www/opencart/admin/config.php
        - sed -i "s/usernamehere/$USER/g" /var/www/opencart/admin/config.php
        - sed -i "s/passwordhere/$PASS/g" /var/www/opencart/admin/config.php2
        - cd /tmp
        - echo "ocuser ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
        - echo 'Cloud-init is done!' >> /tmp/finished.txt


    - name: "Start and enable services"
      service: "name={{ item }} state=restarted enabled=yes"
      with_items:
        - apache2
        - ssh