---
- hosts: localhost
  connection: local
  become: yes
  become_user: root

  vars_files:
    - /tmp/vars.json

  pre_tasks:
    - name: "Install packages"
      apt: 
        name:
          - apache2
          - git
          - php
          - php-mysql
          - libapache2-mod-php
          - php-cli
          - php-common
          - php-intl
          - php-gd
          - php-mbstring
          - php-xml
          - php-zip
          - php-curl
          - php-xmlrpc
          - unzip
          - open-vm-tools
          - mysql-client

  tasks:
    - name: "Clone OpenCart demo from Github"
      git:
        repo: "https://github.com/jsenicka/opencart-demo.git"
        depth: 1
        dest: "/tmp/opencart"

    - name: "Move OpenCart files to /var/www"
      command: "mv /tmp/opencart /var/www/"

    - name: "Write apache configuration to opencart.conf"
      copy:
        content: |
          <VirtualHost *:80>
            ServerName www.opencart.vcf.local
            DocumentRoot /var/www/opencart
            <Directory /var/www/opencart/>
              AllowOverride All
              allow from all
            </Directory>
          </VirtualHost>
          <VirtualHost *:8080>
            ServerName www.opencart.vcf.local
            DocumentRoot /var/www/opencart
            <Directory /var/www/opencart/>
              AllowOverride All
              allow from all
            </Directory>
          </VirtualHost>
        dest: "/etc/apache2/sites-available/opencart.conf"

    - name: "Create an application user named ocuser"
      user:
        name: "ocuser"
        password: "{{ db_password }}"
        shell: "/bin/bash"
        groups: "sudo"

    - name: "Copy OpenCart files to /var/www/html"
      command: "{{ item }}"
      with_items:
        - chown -R www-data.www-data /var/www/opencart
        - chmod -R 775 /var/www/opencart
        - sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/g" /etc/ssh/sshd_config
        - cd /etc/apache2/sites-available/
        - a2ensite opencart.conf
        - a2dissite 000-default.conf
        - echo "[client]" >> /etc/mysql/mysql.conf.d/mysqld.cnf
        - echo "user=ocuser" >> /etc/mysql/mysql.conf.d/mysqld.cnf
        - echo "password={{ db_password }}" >> /etc/mysql/mysql.conf.d/mysqld.cnf
        - sed -i "s/MOAD Electronic Super Store/Holodeck Aria Assembler Fixed Network Lab/g" /var/www/opencart/install/opencart.sql
        - mysql -u {{ db_user }} -h ${{ db_ip }} -e 'source /var/www/opencart/install/opencart.sql'
        - mysql -u {{ db_user }} -h ${{ db_ip }} -e "INSERT INTO oc_user (user_id,user_group_id,username,password,salt,firstname,lastname,email,image,code,ip,status,date_added) VALUES (1,1,'admin','5feaa046f6927df3d744007ec1491dba838f672e','c4wnfrq9J','demo','user','admin@admin.com','none','none','none',1,'2019-01-31 06:29:09')" opencart
        - sed -i "s/frontendiphere/{{ ansible_ssh_host }}/g" /var/www/opencart/config.php
        - sed -i "s/dbiphere/${{ db_ip }}/g" /var/www/opencart/config.php
        - sed -i "s/usernamehere/{{ db_user }}/g" /var/www/opencart/config.php
        - sed -i "s/passwordhere/{{ db_password }}/g" /var/www/opencart/config.php
        - sed -i "s/frontendiphere/{{ ansible_ssh_host }}/g" /var/www/opencart/admin/config.php
        - sed -i "s/dbiphere/${{ db_ip }}/g" /var/www/opencart/admin/config.php
        - sed -i "s/usernamehere/{{ db_user }}/g" /var/www/opencart/admin/config.php
        - sed -i "s/passwordhere/{{ db_password }}/g" /var/www/opencart/admin/config.php2
        - echo "ocuser ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

    - name: "Start and enable services"
      service: "name={{ item }} state=restarted enabled=yes"
      with_items:
        - apache2
        - ssh