---
- hosts: localhost
  connection: local
  become: yes
  become_user: root

  vars_files:
    - /tmp/vars.json

  pre_tasks:
    - name: Wait for automatic system updates
      shell: "while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 1; done;"
  
    - name: "Install packages"
      apt: 
        name:
          - apache2

  tasks:
    - name: "Start and enable services"
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - apache2